### ISSUE TITLE
Means to delete [and set the startup] app from springboard

### ISSUE THREAD

**Issue by joerick** [tingbot/springboard#10]
Currently there is no way to delete the apps from Springboard. I'd like to add a feature to allow this - I'm currently thinking a long touch on the app would open a dialog that contains a delete button. Would also be a good place to put an option to run the app at Tingbot startup.

**Comment by omgmog** [comment]
As indicated in #11 I've been playing with this a bit. 

Perhaps some icons at the bottom left/right for "delete app" and "start at boot" would work.

![screen shot 2016-09-27 at 16 12 27](https://cloud.githubusercontent.com/assets/50949/18879712/40931c9e-84cd-11e6-83db-3c6a0330260e.png)

**Comment by joerick** [comment]
Hey @omgmog thanks for this. While your solution does have clear advantages (discoverability) I've checked with the designers and we're going to stick with the menu idea to give us more freedom down the line to do more with app-specific options.

**Comment by joerick** [comment]
Fixed in 827a86227afc638293bad6859480bc61e6ee43b4
