### ISSUE TITLE
Different click behavior for settings and app

### ISSUE THREAD

**Issue by marcelogaio** [tingbot/springboard#12]
When I click on the top bar (open settings) the event is "on release", but when I click to open the app, it's "on press".
It might improve the user experience if the app is also opened "on release", allowing the user to "cancel" the click by moving the finger to the menu bar
Cheers!

**Comment by joerick** [comment]
Good idea. Actually, touch and hold on an app will soon open a little dialog with settings for an app, so users will be able to cancel from there.
