### ISSUE TITLE
Peripheral Devices, Wi-fi strengh, ethernet etc. show on Home Screen when active

### ISSUE THREAD

**Issue by kennysmed** [tingbot/springboard#4]
Here are the Peripheral Device icons:
_**Note** Attachments may appear invisible due to transparency_

![00 - icon sheet](https://cloud.githubusercontent.com/assets/11627783/15786895/f7b226da-29b6-11e6-93a2-451ecb5457a1.png)
![01 - wifi](https://cloud.githubusercontent.com/assets/11627783/15786897/f7b7ea66-29b6-11e6-950d-6f1fe944ca34.png)
![02 - ethernet](https://cloud.githubusercontent.com/assets/11627783/15786896/f7b39c68-29b6-11e6-83e2-693aef9c3868.png)
![03 - game controller](https://cloud.githubusercontent.com/assets/11627783/15786899/f7b9eb18-29b6-11e6-95b1-eda75a578ede.png)
![04 - cross tick error](https://cloud.githubusercontent.com/assets/11627783/15786898/f7b94dd4-29b6-11e6-8d1f-a70b3a70d117.png)
![05 - locked unlocked](https://cloud.githubusercontent.com/assets/11627783/15786900/f7bfae18-29b6-11e6-8a17-a7acf33b4125.png)
![06 - keyboard mouse](https://cloud.githubusercontent.com/assets/11627783/15786902/f7de8068-29b6-11e6-916d-0f97a5e199c6.png)
![07 - colour dropper](https://cloud.githubusercontent.com/assets/11627783/15786901/f7dde2e8-29b6-11e6-98ed-8d914b19988d.png)
![08 - tingbot text logo](https://cloud.githubusercontent.com/assets/11627783/15786903/f7eba446-29b6-11e6-86e4-f317940268b0.png)
![09 - page dots](https://cloud.githubusercontent.com/assets/11627783/15786904/f7ee704a-29b6-11e6-9882-a2cb295f8e38.png)
![10 - tingbot t icon](https://cloud.githubusercontent.com/assets/11627783/15786905/f7f4f9b0-29b6-11e6-9a68-565cf42ef958.png)

Sliced individual icons to follow...

**Comment by joerick** [comment]
Done
